---
apiVersion: v1
kind: Namespace
metadata:
  name: bitsofinfo

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: bof-ingress-info
  namespace: bitsofinfo

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bof-ingress-info
rules:
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bof-ingress-info
  namespace: bitsofinfo
subjects:
- kind: ServiceAccount
  name: bof-ingress-info
  namespace: bitsofinfo
roleRef:
  kind: ClusterRole
  name: bof-ingress-info
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bitsofinfo
  name: kubernetes-ingress-info
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-ingress-info
  template:
    metadata:
      labels:
        app: kubernetes-ingress-info
    spec:
      serviceAccountName: bof-ingress-info
      containers:
        - name: kubernetes-ingress-info
          image: bitsofinfo/kubernetes-ingress-info:1.0.3
          ports:
            - name: info-port
              containerPort: 8081
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /
              port: 8081
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          command:
            - "info.py"
          args:
            - "--listen-port"
            - "8081"
            - "--load-config-mode"
            - "cluster"
            - "--enable-cache"
            - "--cache-ttl-seconds"
            - "30"
            - "--cache-dir"
            - "/opt/kubernetes-ingress-info/cache"


---
apiVersion: v1
kind: Service
metadata:
  namespace: bitsofinfo
  name: kubernetes-ingress-info
spec:
  selector:
    app: kubernetes-ingress-info
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 31311
    targetPort: info-port

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: bitsofinfo
  name: kubernetes-ingress-info
spec:
  rules:
    - host: kubernetes-ingress-info.local
      http:
        paths:
          - backend:
              serviceName: kubernetes-ingress-info
              servicePort: 31311
